version: '3.9'

services:
    communities-service:
        container_name: communities-service
        image: razom-pay/communities-service:dev
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env.production.local
        volumes:
            - ../.logs/communities:/var/log/services/communities
        networks:
            - razom-pay

networks:
    razom-pay:
        external: true
